### ISSUE TITLE
Adding button

### ISSUE THREAD

**Issue by lostroom** [praveenb-ios/PBDataTableView#1]
Hello praveenb!

Your data grid look great! Is it possible to insert in cell UIButton? For example - last column contain buttons instead of string and after touch works segue with parameters from row? I am trying to do it, but not sure, that it possible.

Thanks a lot

**Comment by praveenb-ios** [comment]
I have updated the code as you have mentioned, please make sure to use on APP Delegate
    **var numberOfColumns: Int!  
    var cellLastColumnButtonEnable: Bool = false**
by default it will be false

While Assigning the dataTableview mention 
**ApplicationDelegate.cellLastColumnButtonEnable = true
dataTableView.lastColumnButtonHeaderName = "Edit"**
as in my example ViewController Class

Below is the delegate function will be called after you click on Edit button.
**tableViewCellEditButtonTapped(indexPath: NSIndexPath)** 

Please rate me if you like the control.

**Comment by praveenb-ios** [comment]
I have updated the code as you have mentioned, please make sure to use on APP Delegate
    var numberOfColumns: Int!    
    var cellLastColumnButtonEnable: Bool = false
by default it will be false

While Assigning the dataTableview mention 
ApplicationDelegate.cellLastColumnButtonEnable = true
dataTableView.lastColumnButtonHeaderName = "Edit"
as in my example ViewController Class

Below is the delegate function will be called after you click on Edit button.
tableViewCellEditButtonTapped(indexPath: NSIndexPath) 

Please rate me if you like the control.

**Comment by praveenb-ios** [comment]
Please check now. I have updated as per your requirement.

Rate me if you like the control.

Thanks,
Praveen B
